# Site settings
title: NOW FINE plc
email: nowfine.nf@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  just want to touch jekyll gem, никогда не хотел быть блоггером,
  надеюсь никогда им и не стану.8)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://con.tom.ru" # the base hostname & protocol for your site
twitter_username: iconco
github_username:  nowfine

# Build settings
markdown: kramdown
