# Site settings
title: NOW FINE plc
email: nowfine.nf@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  just want to touch jekyll gem, никогда не буду блоггером,
  да и не надо мне этого
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: iconco
github_username:  nowfine

# Build settings
markdown: kramdown
